# Generated by Django 5.2.5 on 2025-09-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossprepapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='trial_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bossprepapi.trialquestion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=128),
        ),
    ]
